name: CI + Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install linters
        run: |
          npm install -g stylelint stylelint-config-standard htmlhint jshint

      - name: Lint HTML
        run: htmlhint 

      - name: Lint CSS
        run: stylelint "assets/css/**/*.css" --fix || true

      - name: Lint JS
        run: jshint assets/js/ || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          

          

